# Generated by Django 6.0 on 2025-12-17 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_producto_disponible_producto_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('etiqueta', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
            ],
        ),
    ]
